Perimetro e Area do quadrado
// Disciplina   : Programação de soluções computacionais
// Professor   : Eduardo Nascimento
// Descrição   : perimetro e área do quadrado
// Autor(a)    : Erika G., Larissa C., Diego H., Sidcley B., Vitor
// Data atual  : 13/03/2023
Var
L: real

Inicio
escreva("Qual a altura do quadrado? ")
leia(L)
escreval("O Perimetro é: ", 4*L)
escreval("área do quadrado é: ", L*L)

Fimalgoritmo