Algoritmo "Quociente e resto "
// Disciplina   : Programação de soluções computacionais
// Professor   : Eduardo Nascimento
// Descrição   : Quociente e resto de um número
// Autor(a)    : Erika G., Larissa C., Diego H., Sidcley B., Vitor
// Data atual  : 13/03/2023

Var
n1: inteiro
n2: inteiro


Inicio

escreva("Digite um número inteiro:")
leia(n1)
escreva("Digite um outro número inteiro: ")
leia(n2)
escreval("quociente: ", n1/n2)
escreval("Resto: ", n1%n2)

Fimalgoritmo