Algoritmo "volume da lata"
// Disciplina   : Programação de soluções computacionais
// Professor   : Eduardo Nascimento
// Descrição   : Calcular o valor do volume de uma lata de oleo
// Autor(a)    : Erika G., Larissa C., Diego H., Sidcley B., Vitor
// Data atual  : 13/03/2023

Var
R: real
H: real


Inicio
escreva("Qual é o raio da lata de óleo? ")
leia(R)
escreva("Qual é a altura da late de óleo? ")
leia(H)
escreval("O valor do volume da lata de óleo será: ", 3.14159*(R*2)*H)

Fimalgoritmo