Algoritmo "MediaAritmetica"
// Disciplina   : Programação de soluções computacionais
// Professor   : Eduardo Nascimento
// Descrição   : Calcular a média aritmética das notas dadas.
// Autor(a)    : Erika G., Larissa C., Diego H., Sidcley B., Vitor
// Data atual  : 13/03/2023

Var
X1: real
X2: real


Inicio
Escreva("Primeira nota: ")
leia(X1)
escreva("Segunda nota:")
leia(X2)
escreval("Média aritmética: ", (X1+X2)/2)


Fimalgoritmo