Algoritmo área e perimetro da circuferência
// Disciplina   : Programação de soluções computacionais
// Professor   : Eduardo Nascimento
// Descrição   : perimetro e área de uma circuferência
// Autor(a)    : Erika G., Larissa C., Diego H., Sidcley B., Vitor
// Data atual  : 13/03/2023

Var
R: real

Inicio
Escreva("Qual é o raio da circuferência?")
leia(R)
escreval("A área da circuferência é: ", (R*R)*3,14)
escreval("Perimetro da área é: ", 2*3,14*R)

Fimalgoritmo