Algoritmo "Conversão"
// Disciplina   : Programação de soluções computacionais
// Professor   : Eduardo Nascimento
// Descrição   : Conversão da temperatura de Fahrenheit para Celsius
// Autor(a)    : Erika G., Larissa C., Diego H., Sidcley B., Vitor
// Data atual  : 13/03/2023

Var
F: real

Inicio

escreva("Digite a temperatura em Fahrenheit: ")
leia(F)
escreval("A temperatrura em Ceslsius é: ", (f-32)/1,8)


Fimalgoritmo