Algoritmo "semnome"
// Disciplina   : Programacao de solucoes computacionais
// Professor   : Gilson Damaso
// Descrição   : hm/h para m/s
// Autor(a)    :
// Data atual  : 4/13/2023
Var
// Seção de Declarações das variáveis 
velocidade: inteiro
metros: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite quantos km/h o carro estava")
leia(velocidade)

metros <- velocidade/3.6
escreval("o carro estava a ", metros, " m/s")
Fimalgoritmo