Algoritmo "semnome"
// Disciplina   : programacao de solucoes computacionais
// Professor   : Gilson Damaso
// Descrição   : resultado de divisao
// Autor(a)    :
// Data atual  : 4/13/2023
Var
// Seção de Declarações das variáveis 

 n1,n2: inteiro
 resultado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("digite o dividendo")
leia(n1)
escreval("digite o divisor")
leia(n2)

resultado <- n1/n2
escreval("a divisao deu", resultado)


Fimalgoritmo